### ISSUE TITLE
Zwei App: Recreation of The Public Transport

### ISSUE THREAD

**Issue by PDesire** [tpt-research/thepublictransport-app#26]
Hey mates,

The current code of The Public Transport app is kinda aged now. Also somehow a bit bad, but at least it worked :D 

Anyway. here's some news: The Code itself won't be developed anymore. but it will be replaced. The new app will be called "Zwei" which is the German word for "two" which sounds like the word "to" (in meaning of traveling to some place). The data structure and the app will be completely redone, the code will become better and should be available to anyone.

Also we will try to add more free software to this project to make the rebuild and the reproduction from source to binary even easier. It will be based on **Flutter** of course again, but this time with the option of availabillity for any platform.

Also one huge disclaimer: Due to the complete rework without using any code from TPT, the app will be relicensed in **LGPLv3** and Apache. I want to contribute to the open source community and following my mindset that **PUBLIC** transport should be open for the **PUBLIC** too.

This will also affect the data structure of our Shibi and Shuvi services, so also some backend work needs to be done.

Under this Issue, you can add feature requests, helping me in the recreation process and of course ask questions.

Stay tuned !

Tristan Marsell

**Comment by JohnnyJTH** [comment]
Did this die?

**Comment by PDesire** [comment]
Ok I was to ambitious with my working capacity on this project. This will be discontinued but feel free to fork everything.
